//User Actions

export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const REGISTER_USER = "REGISTER_USER"
export const DELETE_USER = "DELETE_USER"
export const RESET_PASSWORD = "RESET_PASSWORD"
export const LOAD_USER = "LOAD_USER"
export const ERROR_USER = "ERROR_USER"
export const CURRENT_USER = "CURRENT_USER"

// Product Actions
export const ADD_PRODUCT="ADD_PRODUCT"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const GET_PRODUCT_BY_ID="GET_PRODUCT_BY_ID"
export const GET_PRODUCTS="GET_PRODUCTS"
export const LOAD_PRODUCT="LOAD_PRODUCT"
export const ERROR_PRODUCT="ERROR_PRODUCT"
export const BUY_PRODUCT="BUY_PRODUCT"